services:
    redis:
        image: redis:7-alpine
        container_name: proptrep_redis
        ports:
            - "6379:6379"
        restart: unless-stopped
    db:
       image: postgres:16
       container_name: promptrep-db
       environment:
          POSTGRES_DB: ${POSTGRES_DB}
          POSTGRES_USER: ${POSTGRES_USER}
          POSTGRES_PASSWORD: ${POSTGRES_PASSWORD} 
       ports:
           - "5432:5432"
       volumes:
           - postgres_data:/var/lib/postgresql/postgres_data
       restart: unless-stopped

volumes:
  postgres_data:
    driver: local