# Generated by Django 6.0.1 on 2026-01-17 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='message',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
