# Generated by Django 6.0.1 on 2026-01-20 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0008_comment_dislikes_alter_comment_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='capitulo_nro',
            field=models.IntegerField(default=1),
        ),
    ]
