# Generated by Django 6.0.1 on 2026-01-27 18:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0009_comment_capitulo_nro'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_reviewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comment',
            name='red_flags',
            field=models.ManyToManyField(blank=True, related_name='red_flags', to=settings.AUTH_USER_MODEL),
        ),
    ]
