# Generated by Django 6.0.1 on 2026-01-28 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0011_report'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='is_reviewed',
            new_name='alreadyReported',
        ),
    ]
