# Generated by Django 6.0.1 on 2026-02-26 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0012_rename_is_reviewed_comment_alreadyreported'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
