# Generated by Django 6.0.1 on 2026-01-13 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Volcano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del Volcán')),
                ('location', models.CharField(max_length=200, verbose_name='Ubicación')),
                ('height', models.IntegerField(verbose_name='Altura')),
                ('unit', models.CharField(default='m', max_length=10, verbose_name='Unidad')),
                ('type', models.CharField(max_length=100, verbose_name='Tipo de Volcán')),
                ('magma', models.CharField(max_length=100, verbose_name='Tipo de Magma')),
                ('eruptions', models.TextField(verbose_name='Historial de Erupciones')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Comentarios')),
            ],
        ),
    ]
