# Generated by Django 6.0.1 on 2026-01-27 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportticket',
            name='categoty',
            field=models.CharField(choices=[('request_deletion', 'Baja de Cuenta'), ('comment_report', 'Reporte de Comentario')], default='request_deletion', max_length=20),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='related_comment_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
