# Generated by Django 6.0.1 on 2026-02-18 19:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('direct_messages', '0002_chatclear'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='hidden_for',
            field=models.ManyToManyField(blank=True, related_name='stored_chats', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='conversation',
            name='is_active',
            field=models.ManyToManyField(blank=True, related_name='closed_chats', to=settings.AUTH_USER_MODEL),
        ),
    ]
